### PR TITLE
update chart with latest data

### PR DESCRIPTION
**Pull request by icaliman**
Frequently chart is not displaying the last data from scope. This happens when data changes repeatedly.

With these changes chart is updated with the latest data.

Thank you for a good project!

### CODE REVIEW

**Comment by Balrog30** [comment]
You must be updating very frequently for that to have been an issue.  I don't see any issue with this Pull Request.  I'd merge it on the spot, but I haven't tested it.

**Comment by Balrog30** [comment]
Reading the [documentation for $timeout](https://code.angularjs.org/1.2.28/docs/api/ng/service/$timeout), it would appear that what you are looking for is `$timeout.cancel(promise)` where promise the return from the function used to register the delayed function.  I think to do what you're trying to do you need to capture the promise generated inside the `if ((!draw.triggered && ($scope.chart !== undefined))` block at the top of the function and then `$timeout.cancel(promise)` that, then re-register the delayed function.

Now, all that being said, I don't think you're solving anything by doing this.  AngularJS has pretty reliable dirty checking.  If the re-draw is not being triggered for your data then most likely you are either changing your data so fast that the chart drawing can't keep up, or you are changing your data outside of [$scope.$apply()](https://code.angularjs.org/1.2.28/docs/api/ng/type/$rootScope.Scope#$apply) such that your change does not trigger a `$digest()`. If this is the case then angular may not be notifying angular-google-chart that it needs to redraw.   This being said, all code run from within a controller is automatically inside a `$scope.$apply()`, and calling it in this context would produce an error.  If you are modifying the data from within a service, another directive, or some other code outside of angular, then you would need to wrap your changes in `$scope.$apply()`.

I hope this helps...

**Comment by icaliman** [comment]
Yes you are right with `$timeout.cancel(promise)`! I used online editor and made a typo, locally I have the correct fix, maybe copy/paste would be better :)

I am modifying the data inside a `$scope.$watch()`, so a `$digest()` is triggered.

In my app data is changing very frequently and this fix solves the issue.

Thank you!

**Comment by Balrog30** [comment]
Ok, I checked it out with no errors this time.  I'll have to trust that this handles your edge case, because I've not been able to reproduce the issue you had.

**Comment by Leward** [comment]
I also experienced the same case and this fix was helpful. Thank you.

**Pull request merged**
