### PR TITLE
Added missing on-page event that currently IS supported by google cha…

### PR DESCRIPTION
**Pull request by smiffy6969**
…rts for paging in tables.

### CODE REVIEW

**Comment by smiffy6969** [comment]
I have altered things a little to allow you to pull in these two fixes how you see fit. I understand your reluctance to add onDeselect but please at least read the commit messages.

**Comment by Balrog30** [comment]
So, you've made me put some thought into this.  You're the first to request an event that is not exposed by chartWrapper be added to the directive itself.  There are many events that are supported only by one or two chart types.  I wonder if, perhaps, we could handle everything by building handlers more like this:

```HTML
<div google-chart chart="myChart" event-handlers="chartHandlers"></div>
```

```JavaScript
$scope.chartHandlers = {
  select: function (selectedItem){
    //some stuff
  },
  regionClick: function (region){
    //handle regionClick event for geoChart
  },
  rangechange: function (start, end){
    //Handle Range Change event for Annotation Charts
  }
};
```

This could be less specific by just passing return value directly to user instead of splitting the params.  This way of handling events covers pretty much all of them in one go, and keeps the HTML from being cluttered with a dozen event handler definitions.  A combination of both methods could also be used for flexibility. I'm not sure what the best way to handle a case where both methods are used (run both?  run only one?  which one?).

This is just an alternative suggestion, of course.  The problem with having handlers for specific chart type events is that it commits us to keeping up with the Google project.  Not that it's that much work, but it's not really that necessary to do all that extra work.

I like the passion that you have for your suggested changes, but there are many ways to do any one thing.  For example, if you don't like the way google handles "deselect", your own select handler that then splits the event into select and deselect events.  I'd love to hear from @bouil about your proposed deselect event, but I still feel that this project is "just a wrapper", and it's not necessary to change the behavior of the underlying library.  If you don't like the way they handle deselects, you can always [let them know](https://code.google.com/p/google-visualization-api-issues/issues/list).  I'd personally much rather put effort to things like supporting features of the Charts API that you just can't with with right now (like dashboards and chart controls).

Again, all my opinion... I'm only one user.  I would love it if someone else set me straight if I'm wrong.

**Comment by smiffy6969** [comment]
I like your method, much cleaner...... I look at things far more simplistically than most... Quite simply I do not see this as a wrapper, I see it as a charting tool, what it depends on is neither here nor there for me, the fact is I need to do a job and I need a charting tool.

In an ideal world, yes we should probably follow the path of the google charts wrapping it nicely, but we are far from an ideal world. What we are doing here is extending base charting to work better with angular. In an ideal world the charting library would work correctly (getting this changed at source is not an option, I have tried many times in vein to push changes of various guises to google and failed in most cases).

So I go back to our non ideal world, in which a tool is not working as expected, and is altered to work in a more logical manner, the insides of which are immaterial to most, the ideals of which are immaterial to most..... Seriously, people come to git hub looking for tools to do jobs, and use XYZ because it works, not because it supports the panda populations in asia, my point is they need what works and don't care about the fundamentals.

In the end, this wrapper will not be viable tool for too long, it's prime use is to bring google charts to angular with ease.... google charts can pretty much be used natively in angular as is, but I was having issues with IE9 for some reason so switched to this. The upcoming web components revolution is doing away with tools like this, in a perfect world web components will with jQuery, native JS, in angular and so on (I am currently writing web components that do just this, using polymer but to be used in any platform).

I chose this for IE9 support, I could have been a little less lazy and found a solution to the problem of native google charts and IE9 with angular in my situation but then the world is far from ideal and we all have deadlines to work to.

All I can say is try to see this as less of a wrapper, more of an extension of an existing tool, and we all know that extensions means evolution for the extended tool, i.e. addition of features ;)

glad I sparked some interest!

**Comment by smiffy6969** [comment]
Don't say I didn't try...... ;)

https://code.google.com/p/google-visualization-api-issues/issues/detail?id=1977&thanks=1977&ts=1431072938

**Comment by bouil** [comment]
@smiffy6969 This directive is not a charting tool, it's a wrapper to use without much pain the google charting tool. The goal of the directive is load the google chart api inside AngularJS (after bootstraping angular) and to redraw the chart automatically when the data are changed. I don't think it's a good idea to add too much feature that are already provided by the Google Chart API (with or without workarounds, such as the deselect event). 

@Balrog30 : I like you idea having an "event-handlers" attribute grouping all different kind of events. I suppose we could add this to support the on-page event, and support also on-select and on-ready event f present in this event-handlers object. We should also add a deprecation warning for the on-select and on-ready event, while still supporting them for a while. 

But (and thinking in the same time as writing this comment) you're right that we would end up adding and following any kind on event on any new chart google chart may add. I don't have the time for that, and again I don't think you should always being catching up on Google Chart features.

From here i see 2 options.

1. We add a meta object such as @Balrog30 described, generic so the "key" of the object is the event name, and the function is the raw chart listeners expected by the google API. The difficulty here is that the parameters of the event listeners doesn't contains the chartWrapper object, and we should make it available to the callback in some way, (without using a wrapping function if possible, to allow the user to remove its listeners using https://developers.google.com/chart/interactive/docs/reference#removelistener )

2. We remove completely any chart-specific event (such the exisiting on-select event) to keep only "on-ready" and "on-error". It would be the user resposability to add any event using its onReady callback function. One can then register it's own events using https://developers.google.com/chart/interactive/docs/reference#addlistener or https://developers.google.com/chart/interactive/docs/reference#addonetimelistener. Removing the listener is straightforward.

Those 2 approachs require a documentation to make it clear how to use events, (and the probable need to use $apply inside them), with samples for the most useful ones.

I would be drastic and would prefer the 2nd option. The on-select event can be kept for a while, marked deprecated with a link to the documentation on how to do it. After some time, it could be removed.

What do you think?

**Comment by Balrog30** [comment]
I'll try to slap some code together tonight with some of the more unusual events and see what I can get to work.  Registering the handlers by key shouldn't be a problem.  Without even specific values we might be able to just dump everything at the user and let them use what they want (ChartWrapper, Chart, the return from the event, etc.).

**Comment by smiffy6969** [comment]
@bouil well there you have it.... either keep this up to date with ALL events, or do not pass on any events (as you suggested).... The fact is you are being selective in some areas as to what events are being passed on and and not so much in others. There are several events I can find for more specific charts/tables that are not here, for example the 'page' event.

So if this cannot be kept up to date, your suggestion is to cripple it by removing all events but on ready and on error.... making using this tool even more of a PITA.

Making this 'tool', 'wrapper' or whatever we wish to call it more convoluted to use because it's easier to upkeep is a bit silly really, removal of on select and forcing the user to implement events after on ready is a bit illogical to me but then thats just my opinion, but then that is only an opinion.

thanks for all your hard work on this wrapper/tool I don't take me the wrong way, I am appreciative, just very pragmatic about life and things, I will investigate IE9 issues with native google-charts and move back to this I think.

kind regards

Paul

**Pull request closed without merging**
